### PR TITLE
Serve web connectivity 0.5 to PK

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Implements https://github.com/ooni/probe/issues/2499

### CODE REVIEW

**Review by bassosimone — APPROVED** [review]
🐳

**Comment by FedericoCeratto** [comment]
1.0.59~pr695-103 deployed on test and later on FSN

**Comment by FedericoCeratto** [comment]
Rolling back to 1.0.58~pr678-82 as discussed after running for 2 days.

**Comment by FedericoCeratto** [comment]
Closing the PR. There is no practical benefit in merging the code changes.

**Pull request closed without merging**
